### ISSUE TITLE
程序运行报错（已解决）

### ISSUE THREAD

**Issue by jokerdxr** [qianlishun/TermiWatchWidget#1]
作者您好，我用的是Xcode15.0.1，运行的时候出现如下报错，请问该怎么解决呢？
<img width="905" alt="image" src="https://github.com/qianlishun/TermiWatchWidget/assets/32271749/a1b910df-bd18-48f9-8c94-0583ee81fcf5">

**Comment by qianlishun** [comment]
我写错了一个和风天气解析的地方，修复了，你看下commit对着改一下或者再拉个版本吧。

4d5f29baa09e513fd8575a0446fc33532eb9de73

**Comment by jokerdxr** [comment]
非常感谢作者的回复，代码跑通了，能正常运行。

**Comment by qianlishun** [comment]
> 非常感谢作者的回复，代码跑通了，能正常运行。

之前你发的那个数据不显示是由于使用的widget机制，数据刷新频率有限制，做不到即时刷新，数据更新会有点滞后。

**Comment by jokerdxr** [comment]
嗯嗯似乎是的，我把手表和手机升级到最新版就好了😁
