### ISSUE TITLE
Signing Certificate Error

### ISSUE THREAD

**Issue by AlphaStrioleno** [qianlishun/TermiWatchWidget#2]
你好，请教一下Bundle Identifier的问题。
我在 Run 的时候总是出现：
Xcode couldn't find any iOS App Development provisioning profiles matching 
我已经按照步骤1，2，3进行了修改。
注：
macOs 版本：14.5
Xcode 版本：Version 15.2
如果我新建一个工程，是可以正常安装到手机上的。

**Comment by qianlishun** [comment]
看看是不是没改全， 或者换一个bundle ID

**Comment by AlphaStrioleno** [comment]
开始是有两个替换不了，后面我又克隆一遍，用VSCode进行全项目的搜索替换，然后进入Xcode更改Team，也出现上面提到的错误。我各种尝试换bundle ID也无法成功。如果是我新建一个iOS的工程，Bundle Identifier会自动生成，是 Organization Identifier + Product Name，不会报错，也可以成功编译并安装到手机上。还可能是什么原因呢。

**Comment by qianlishun** [comment]
我试了一下，先把三个target的team选none，然后批量替换bundleid前缀com.void.TermiWatch为其他的，然后再修改三个target的team，编译成功。 如果非付费账号，需要依次去除三个target下面的weatherkit。

**Comment by AlphaStrioleno** [comment]
谢谢🙏你帮我试，当然还有你的指导。应该是要删除weatherkit。编译成功了，也安装了。但是在Watch软件里面安装的时候会弹出: This app could not be installed at this time。我是直接将 TermiWatchWidget Watch App用Xcode安装到手表上的。是我还有什么遗漏了吗。

**Comment by qianlishun** [comment]
先编译安装TermiWatchWidget到手机，再 编译安装TermiWatchWidget Watch App到手表。

**Comment by AlphaStrioleno** [comment]
是的，但是readme里面好像是在手机上的watch app里面安装。我还有一个问题，如果改变了字体大小，中括号里面的字就不是对齐的了，有什么好办法没有，等宽字体？能设字体吗。

**Comment by qianlishun** [comment]
UI 想修改就去 /TermiWatchWidget Watch App/View/QCommonView.swift 里面改 ，没几行代码

**Comment by AlphaStrioleno** [comment]
![image](https://github.com/user-attachments/assets/a6d4bd7c-6920-4912-b26b-c06cf9ebc9e2)
我是想说改变了字体，中括号对不齐，有什么办法没有。

**Comment by qianlishun** [comment]
本来就是凑的，自己改代码想办法对齐。

**Comment by qianlishun** [comment]
添加默认字体调整标题布局 749850e
